server:
  port: 8085
  http2:
    enabled: true
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: iot-sent-msg
  profiles:
    active: @env@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    ## @FeignClient(value = "服务名r") 设置可以有多个类存在相同的FeignClient 中的value值
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    com.zhengbang.user: INFO

#swagger:
#  enable: true

knife4j:
  enable: true


mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #工作机器ID(0~31) 部分(影响雪花ID)
    workerId: 2
    #数据中心ID--机房 部分(影响雪花ID)(workerId 和 datacenterId 一起配置才能重新初始化 Sequence)
    datacenterId: 10
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
